export const APP_STATE_STORAGE_KEY = "yet-another-app-state";

export const viewLabels = {
  LOG: "LOG",
  LOG_WEIGHT: "LOG_WEIGHT",
  PLAN: "PLAN",
  WORKOUT: "WORKOUT",
  WORKOUT_CREATE: "WORKOUT_CREATE",
  FOOD: "FOOD",
  FOOD_CREATE_MEAL: "FOOD_CREATE_MEAL",
  FOOD_LIST: "FOOD_LIST",
  FOOD_MEALS: "FOOD_MEALS"
};
